import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Historique des commandes",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

export default async function AdminLayout({ children }: RootLayoutProps) {
  return (
    <>
      <section>{children}</section>
    </>
  );
}
