import type { Metadata } from "next";
import { ReactNode } from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
  robots: "noindex",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default async function LoginLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions);
  if (!session?.user.isAdmin) {
    notFound();
  }

  return <>{children}</>;
}
