import type { Metadata } from "next";
import { ReactNode } from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { notFound } from "next/navigation";
import AdminNav from "@/components/admin-nav";

export const metadata: Metadata = {
  title: "Espace admin",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

type RootLayoutProps = {
  children: ReactNode;
};

export default async function AdminLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions);
  if (!session?.user.isAdmin) {
    notFound();
  }

  return (
    <>
      <AdminNav />
      <section>{children}</section>
    </>
  );
}
