import "@/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { ReactNode } from "react";
import { Navbar } from "@/components/nav-bar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import SessionProvider from "@/context/next-auth-provider";
import { ThemeProvider } from "@/context/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Poppins } from "next/font/google";
import Footer from "@/components/footer";
import { ShoppingCartProvider } from "@/context/shopping-cart-provider";

const poppins = Poppins({ weight: ["400", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    maximumScale: 1,
};

export default async function RootLayout({ children }: { children: ReactNode }) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="fr" suppressHydrationWarning>
            <body className={poppins.className} suppressHydrationWarning>
                <SessionProvider session={session}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <ShoppingCartProvider>
                            <Navbar session={session} />
                            <main className="container min-h-[95dvh]">{children}</main>
                            <Footer session={session} />
                            <Toaster />
                        </ShoppingCartProvider>
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
